### ISSUE TITLE
[FEATURE] Information-main-reaserch

### ISSUE THREAD

**Issue by JoohwanSeo** [B-09-NBC-Final/Health-Protect-Me#10]
---

name: 'FEAT'
about: 코드의 구조나 디자인을 변경하되 기능은 그대로 유지
title: '[FEAT] '
labels: ''
assignees: ''

---

## To-Do

- [ ] 설문지 중에 인풋으로 관리되는 항목 페이지 구성
- [ ]  다음 설문으로 넘어가는 버튼 제작
- [ ]  설문지 중에 버튼으로 관리되는 항목 페이지 구성

## ETC
![information-reaserch](https://github.com/user-attachments/assets/01a4726e-63e4-44f8-bc67-b67d78d73224)

### 작업이 완료 예정인 시점을 적어주세요

미정 -
