### ISSUE TITLE
feat/postingRegister UI

### ISSUE THREAD

**Issue by JoohwanSeo** [B-09-NBC-Final/Health-Protect-Me#20]
---

name: 'FEAT'
about: 코드의 구조나 디자인을 변경하되 기능은 그대로 유지
title: '[FEAT] '
labels: ''
assignees: ''

---

### 어떤 기능을 추가했는지 작성해주세요.
 게시글 등록 페이지에 대한 레이아웃 구성

## To-Do

- [ ] 카테고리 태그 구성
- [ ] title, content 인풋 구성
- [ ] image 첨부 구성
- [ ] 버튼 구성

## ETC
![posting-1](https://github.com/user-attachments/assets/4789641f-3bbd-4059-8b11-6fc5e028c3ba)
![posting-2](https://github.com/user-attachments/assets/e244751e-c246-4e20-a1d1-9614eab3eb5f)

### 작업이 완료 예정인 시점을 적어주세요
미정 -
