### ISSUE TITLE
feat/Kakao API 

### ISSUE THREAD

**Issue by heesu21** [B-09-NBC-Final/Health-Protect-Me#21]
---

name: 'FEAT'
about: 코드의 구조나 디자인을 변경하되 기능은 그대로 유지
title: '[FEAT] '
labels: ''
assignees: ''

---

## To-Do

- [ ]  로그인 요청 및 콜백 처리
- [ ] 액세스 토큰 저장
- [ ] 사용자 정보 요청
- [ ] 사용자 정보 파싱 및 저장
- [ ] 세션 및 사용자 상태 관리
- [ ] 로그아웃 기능 구현
- [ ] 에러 처리
