### ISSUE TITLE
feat/postingRegister API

### ISSUE THREAD

**Issue by JoohwanSeo** [B-09-NBC-Final/Health-Protect-Me#26]
---

name: 'FEAT'
about: 코드의 구조나 디자인을 변경하되 기능은 그대로 유지
title: '[FEAT] '
labels: ''
assignees: ''

---

### 어떤 기능을 추가했는지 작성해주세요.
게시글 작성 및 이미지를 db에 연결하여 등록하는 작업

## To-Do

- [x] title, content  connect to supabase -> insert Table
- [x] image, connect to supabase -> storage(changeTo url) -> insert Table
- [x] Setting the value of user_id  *

### 작업이 완료 예정인 시점을 적어주세요
미정 -
