### ISSUE TITLE
Feat/editAlert - 마이 페이지 알럿 기능 구현

### ISSUE THREAD

**Issue by JoohwanSeo** [B-09-NBC-Final/Health-Protect-Me#300]
---

name: 'FEAT'
about: 코드의 구조나 디자인을 변경하되 기능은 그대로 유지
title: '[FEAT] '
---

### 어떤 기능을 추가했는지 작성해주세요.
- 마이 페이지 내 정보 변경(체중,목적) 시, 알럿창 표시 후 결과 페이지 이동

## To-Do

- [ ] 정보 변경 시, 알럿 기능
- [ ] 체중과 식단 목적 변경 시에만 알럿 활성화
- [ ] 이동 페이지 라우터 설정

### 작업이 완료 예정인 시점을 적어주세요
08.14
