### ISSUE TITLE
feat/info-Detail-Ui

### ISSUE THREAD

**Issue by Elephant24456** [B-09-NBC-Final/Health-Protect-Me#8]
---

name: 'FEAT'
about: 코드의 구조나 디자인을 변경하되 기능은 그대로 유지
title: '[FEAT] '
labels: ''
assignees: ''

---

## To-Do

- [ ] 정보 디테일 UI
- [ ] 식단 카드 리스트 구현하기
- [ ] 추천 운동 리스트 구현하기
