### ISSUE TITLE
feat/headerNav

### ISSUE THREAD

**Issue by heesu21** [B-09-NBC-Final/Health-Protect-Me#9]
---

name: 'FEAT'
about: 코드의 구조나 디자인을 변경하되 기능은 그대로 유지
title: '[FEAT] '
labels: ''
assignees: ''

---

## To-Do

- [ ] 로고 클릭 시 홈으로 가는 기능
- [ ] 로그인 버튼 클릭 시 로그인 창으로 가는 기능 구현 
- [ ] 로그아웃 버튼 클릭 시 홈으로
